### ISSUE TITLE
Is this still available for use?

### ISSUE THREAD

**Issue by bskimball** [nesl247/ibm-driver#1]
I have not tried this package. I have a project I want to use this on. I'd rather use eloquent than doctrine if possible. Any specific set up instructions?

**Comment by nesl247** [comment]
This still works 100%. Here's an example config to put into `app/config/database.php` in the connections array.

```
db2' => [
            'driver' => 'ibm',
            'host' => 'SYSTEM_NAME',
            'username' => 'USERNAME',
            'password' => 'PASSWORD',
        ],
```

The other thing you need to do, unless they finally fixed it, is to change the `fetch` setting at the top to `'fetch' => PDO::FETCH_ASSOC,` because there is a bug in PDO's db2 driver which adds an invalid null character to the field names and breaks `FETCH_OBJECT` which was the default when I wrote this.

**Comment by nesl247** [comment]
Closing this unless any other questions are asked.
